# Independent Pandas Practice
Each question reloads students.csv.

## Question 1
**Rename one column**

Rename 'Name' to 'Student_Name'.

In [4]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below
df=df.rename(columns={
    "Name":"Student_Name"
})


df

   Student_ID Student_Name  Age  Class  Math  Physics  Computer  Average
0         101      Shubham   20  CSE-A    90       88        95       91
1         102         Amit   21  CSE-A    80       76        84       80
2         103        Priya   20  CSE-B    92       94        90       92
3         104        Rahul   22  CSE-B    70       68        72       70
4         105         Neha   21  CSE-C    85       82        88       85
5         106        Karan   20  CSE-C    78       80        79       79
6         107        Sonia   21  CSE-A    96       95        98       96
7         108        Arjun   22  CSE-B    67       70        65       67
8         109         Riya   20  CSE-C    89       91        90       90
9         110        Vikas   21  CSE-A    75       73        78       75

### Checker

In [5]:
print("✅ Correct" if "Student_Name" in df.columns and "Name" not in df.columns else "❌ Incorrect")

✅ Correct

### Reference Solution

In [ ]:
df=df.rename(columns={"Name":"Student_Name"})

## Question 2
**Rename three columns**

Rename Name→Student_Name, Computer→Computer_Science, Class→Section.

In [6]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below
df=df.rename(columns={
    "Name":"Student_Name",
    "Computer":"Computer_Science",
    "Class":"Section"
})


df

,Student_ID,Student_Name,Age,Section,Math,Physics,Computer_Science,Average
0,101,Shubham,20,CSE-A,90,88,95,91
1,102,Amit,21,CSE-A,80,76,84,80
2,103,Priya,20,CSE-B,92,94,90,92
3,104,Rahul,22,CSE-B,70,68,72,70
4,105,Neha,21,CSE-C,85,82,88,85
5,106,Karan,20,CSE-C,78,80,79,79
6,107,Sonia,21,CSE-A,96,95,98,96
7,108,Arjun,22,CSE-B,67,70,65,67
8,109,Riya,20,CSE-C,89,91,90,90
9,110,Vikas,21,CSE-A,75,73,78,75

### Checker

In [7]:
print("Run your code and inspect the result. Independent exercise.")

Run your code and inspect the result. Independent exercise.

### Reference Solution

In [ ]:
# Reference solution

## Question 3
**Drop first row**

Remove the first row.

In [8]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below
df=df.drop(index=[0])

df

   Student_ID   Name  Age  Class  Math  Physics  Computer  Average
1         102   Amit   21  CSE-A    80       76        84       80
2         103  Priya   20  CSE-B    92       94        90       92
3         104  Rahul   22  CSE-B    70       68        72       70
4         105   Neha   21  CSE-C    85       82        88       85
5         106  Karan   20  CSE-C    78       80        79       79
6         107  Sonia   21  CSE-A    96       95        98       96
7         108  Arjun   22  CSE-B    67       70        65       67
8         109   Riya   20  CSE-C    89       91        90       90
9         110  Vikas   21  CSE-A    75       73        78       75

### Checker

In [9]:
print("Run your code and inspect the result. Independent exercise.")

Run your code and inspect the result. Independent exercise.

### Reference Solution

In [ ]:
# Reference solution
df=df.drop(index=[0])

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (4230244877.py, line 2)

## Question 4
**Drop last row**

Remove the last row.

In [15]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below

df=df.drop(index=[-1])

df

KeyError: '[-1] not found in axis'

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [12]:
# Reference solution

## Question 5
**Drop rows by index**

Remove rows with index 1 and 3.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 6
**Drop two columns**

Remove Age and Class.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 7
**Insert constant column**

Insert Bonus_Marks with value 5.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 8
**Insert calculated column**

Create Total=Math+Physics+Computer.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 9
**Move column first**

Move Average to first.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 10
**Move column last**

Move Average to last.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 11
**Set Student_ID index**

Set Student_ID as index.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 12
**Set Student_Name index**

Set Name as index.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 13
**Reset index**

Reset the index.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 14
**Custom index**

Create S1,S2,...

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 15
**Reverse reindex**

Reverse row order with reindex.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 16
**Reindex missing labels**

Add X1,S2 labels.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 17
**Save CSV**

Save student_report.csv.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 18
**Rename dict**

Rename using dictionary.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 19
**Rename function**

Convert headers to uppercase.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 20
**Drop duplicates**

Remove duplicate rows.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 21
**Passed column**

Create Passed column.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 22
**Alphabetical columns**

Sort columns alphabetically.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 23
**Backup**

Create backup copy.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 24
**Unique index**

Verify index uniqueness.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution

## Question 25
**Restore**

Restore from backup.

In [ ]:
import pandas as pd

df=pd.read_csv("students.csv")

# Write your solution below


df

### Checker

In [ ]:
print("Run your code and inspect the result. Independent exercise.")

### Reference Solution

In [ ]:
# Reference solution